/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

const ballMaterial = {
  clearcoat: 0.0,
  cleacoatRoughness: 0.1,
  metalness: 0.999,
  roughness: 0.0,
  color: 0xcccccc,
};

export function Model(props: any) {
  //@ts-ignore
  const { nodes, materials } = useGLTF("./website_3d_cumberlandsche.glb");
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.cumberlandsche_abstract.geometry}>
        <meshPhysicalMaterial
          color={ballMaterial.color}
          clearcoat={ballMaterial.clearcoat}
          clearcoatRoughness={ballMaterial.cleacoatRoughness}
          roughness={ballMaterial.roughness}
          metalness={ballMaterial.metalness}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./website_3d_cumberlandsche.glb");
