/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

const ballMaterial = {
  clearcoat: 0.0,
  cleacoatRoughness: 0.1,
  metalness: 0.999,
  roughness: 0.0,
  color: 0xcccccc,
};

export function Model(props: any) {
  //@ts-ignore
  const { nodes, materials } = useGLTF("./website_3d_cumberlandsche.glb");
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.cumberlandsche_abstract.geometry}>
        <meshPhongMaterial
          color={0x0000dd}
          specular={0xffffff}
          combine={THREE.MultiplyOperation}
          shininess={50}
          reflectivity={1}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./website_3d_cumberlandsche.glb");
